#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

SIGTERM_handler()
{
  echo "I hate the kill command"
  rm /var/run/myscript.pid
  exit 0
}

SIGINT_handler()
{
	echo "Y I no love me?!"
}

SIGQUIT_handler()
{
	rm /var/run/myscript.pid
	exit 0
}

trap "SIGTERM_handler" SIGTERM
trap "SIGINT_handler" SIGINT
trap "SIGQUIT_handler" SIGQUIT

pgrep -f 100-pocess_and_pid_file >> /var/run/myscript.pid
while $1
do
	echo "To infinity and beyond"
	sleep 2
done
