#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while IFS= read -r LINE; do
  echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd
